### --------------------------------------------------------
###  Configuration macro for the square optical fiber geometry.
###  This macro simulates a 172 nm (7.21 eV) optical photon.
###  in the active volume.
### --------------------------------------------------------


/run/verbose 0
/event/verbose 0
/tracking/verbose 0
/process/em/verbose 0


### Generation
/Generator/SingleParticle/particle opticalphoton
#/Generator/SingleParticle/min_energy 2.883 eV
#/Generator/SingleParticle/max_energy 2.883 eV
/Generator/SingleParticle/min_energy  7.21 eV
/Generator/SingleParticle/max_energy 7.21 eV


/Generator/SingleParticle/region LINE_SOURCE_EL
#/Generator/SingleParticle/region AD_HOC
#/Generator/SingleParticle/region SingleParticle

#/Generator/SingleParticle/region ACTIVE
#/Generator/SingleParticle/min_costheta 0.6711
/Generator/SingleParticle/min_costheta 0
/Generator/SingleParticle/max_costheta 1



#### SETUP PARAMETERS, Big run #### 
/nexus/random_seed 10476
/Geometry/SquareOpticalFiber/specific_vertex 2.5 -1.5 -5.0023 mm # z-value not relevant here in "LINE_SOURCE_EL" mode
/Geometry/SquareOpticalFiber/ELGap 1 mm
/Geometry/SquareOpticalFiber/pitch 5 mm
/Geometry/SquareOpticalFiber/distanceFiberHolder 2 mm
/Geometry/SquareOpticalFiber/distanceAnodeHolder 5 mm
/Geometry/SquareOpticalFiber/holderThickness 10 mm
/Geometry/SquareOpticalFiber/TPBThickness 2.2 #microns

/SquareOpticalFiber/SquareFiberSD/Output/sipmPath /home/amir/Products/geant4/geant4-v11.0.1/MySims/nexus/SquareFiberMacrosAndOutputs/ELGap=1mm_pitch=5mm_distanceFiberHolder=2mm_distanceAnodeHolder=5mm_holderThickness=10mm/SiPM_hits_x=2.5mm_y=-1.5mm.txt

/SquareOpticalFiber/SquareFiberSD/Output/tpbPath /home/amir/Products/geant4/geant4-v11.0.1/MySims/nexus/SquareFiberMacrosAndOutputs/ELGap=1mm_pitch=5mm_distanceFiberHolder=2mm_distanceAnodeHolder=5mm_holderThickness=10mm/TPB_hits_x=2.5mm_y=-1.5mm.txt





# When using the SaveAllSteppingAction
/nexus/persistency/outputFile /media/amir/9C33-6BBD/NEXT_work/Geant4/nexus/SquareFiber.next

# When NOT using the SaveAllSteppingAction
#/nexus/persistency/outputFile /dev/null


#/Actions/SaveAllSteppingAction/select_volume SiPM
#/Actions/SaveAllSteppingAction/select_volume TPB
#/Actions/SaveAllSteppingAction/select_volume WORLD
#/Actions/SaveAllSteppingAction/select_volume Cap1
#/Actions/SaveAllSteppingAction/select_volume Barrel