### --------------------------------------------------------
###  Configuration macro for the square optical fiber geometry.
###  This macro simulates a 172 nm (7.21 eV) optical photon.
###  in the active volume.
### --------------------------------------------------------


/run/verbose 0
/event/verbose 0
/tracking/verbose 0
/process/em/verbose 0


### Generation
/Generator/SingleParticle/particle opticalphoton
#/Generator/SingleParticle/min_energy 2.883 eV
#/Generator/SingleParticle/max_energy 2.883 eV
/Generator/SingleParticle/min_energy  7.21 eV
/Generator/SingleParticle/max_energy 7.21 eV


## Choose region
/Generator/SingleParticle/region LINE_SOURCE_EL
#/Generator/SingleParticle/region AD_HOC
#/Generator/SingleParticle/region SingleParticle
#/Generator/SingleParticle/region FACE_RANDOM_DIST


#/Generator/SingleParticle/region ACTIVE
#/Generator/SingleParticle/min_costheta 0.6711
/Generator/SingleParticle/min_costheta 0
/Generator/SingleParticle/max_costheta 1


####  SETUP PARAMETERS  ####
/nexus/random_seed 10000
#/Geometry/SquareOpticalFiber/specific_vertex 0 0 -0.0011 mm # face of fiber TPB, "AD_HOC"
/Geometry/SquareOpticalFiber/specific_vertex 0 0 -0.0023 mm # z-value not relevant here in "LINE_SOURCE_EL" mode
#/Geometry/SquareOpticalFiber/specific_vertex 0 0 -0.0011 mm # face of fiber, "FACE_RANDOM_DIST"


/Geometry/SquareOpticalFiber/ELGap 10 mm
/Geometry/SquareOpticalFiber/pitch 15.6 mm
/Geometry/SquareOpticalFiber/distanceFiberHolder 2 mm
/Geometry/SquareOpticalFiber/distanceAnodeHolder 10 mm
/Geometry/SquareOpticalFiber/holderThickness 10 mm
/Geometry/SquareOpticalFiber/TPBThickness 2.2 um 

## Write output hitpoint text files ##
/SquareOpticalFiber/SquareFiberSD/Output/sipmPath /media/amir/9C33-6BBD/NEXT_work/Geant4/nexus/SiPM_hits.txt
/SquareOpticalFiber/SquareFiberSD/Output/tpbPath /media/amir/9C33-6BBD/NEXT_work/Geant4/nexus/TPB_hits.txt


## Write hdf file ##
#When using the SaveAllSteppingAction
#/nexus/persistency/outputFile /media/amir/9C33-6BBD/NEXT_work/Geant4/nexus/SquareFiber.next

# When NOT using the SaveAllSteppingAction
/nexus/persistency/outputFile /dev/null




#/Actions/SaveAllSteppingAction/select_volume SiPM
#/Actions/SaveAllSteppingAction/select_volume TPB
#/Actions/SaveAllSteppingAction/select_volume WORLD
#/Actions/SaveAllSteppingAction/select_volume Cap1
#/Actions/SaveAllSteppingAction/select_volume Barrel



